---
linters:
  enable-all: true
  disable:
    # it should improve to support more known patterns
    - varnamelen
    - nolintlint
    # it isn't our way
    - tagliatelle
    - depguard
    # deprecated linters
    - maligned
    - scopelint
    - golint
    - interfacer
    - exhaustivestruct
    - ireturn
    - varcheck
    - ifshort
    - deadcode
    - nosnakecase
    - structcheck
